default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-aws-credentials
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.1.1
  hooks:
    - id: clang-format
      args: [--style=file, -i]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.2
  hooks:
    - id: ruff
      name: ruff
      entry: ruff
      args: [check, --fix, "--line-length=120", "--ignore=F401,E203"]
      types: [python]
      language: system
      exclude: cases_update
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
    - id: mypy
      name: mypy
      language: python
      files: src/.*\.py
