import pytest
import torch
import unittest.mock as mock
from unittest.mock import MagicMock, patch

from neuronx_distributed.modules.moe.blockwise import (
    _call_bwmm_shard_on_block_kernel,
    BlockwiseMatmulArgs,
    SkipMode,
    ExpertAffinityScaleMode,
    BlockShardStrategy,
    ActivationFunction
)

# Generated by Amazon Q!!!
class TestCallBwmmShardOnBlockKernel:
    
    @pytest.fixture
    def sample_args(self):
        """Create sample BlockwiseMatmulArgs for testing."""
        seq_len, hidden_size = 128, 512
        num_experts, intermediate_size = 8, 2048
        block_size = 128
        
        return BlockwiseMatmulArgs(
            hidden_states=torch.randn(seq_len, hidden_size, dtype=torch.bfloat16),
            expert_affinities_masked=torch.randn(seq_len * num_experts, 1, dtype=torch.bfloat16),
            gate_up_proj_weight=torch.randn(num_experts, hidden_size, 2, intermediate_size, dtype=torch.bfloat16),
            down_proj_weight=torch.randn(num_experts, intermediate_size, hidden_size, dtype=torch.bfloat16),
            token_position_to_id=torch.arange(seq_len, dtype=torch.int32),
            block_to_expert=torch.randint(0, num_experts, (seq_len // block_size,), dtype=torch.int32),
            block_size=block_size,
            conditions=torch.ones(seq_len // block_size, dtype=torch.int32),
            dtype=torch.bfloat16,
            is_tensor_update_accumulating=True,
            expert_affinities_scaling_mode=ExpertAffinityScaleMode.POST_SCALE,
            block_sharding_strategy=BlockShardStrategy.HI_LO,
            skip_dma=SkipMode(False, False),
            kernel_act_fn=ActivationFunction(1)
        )

    @patch('neuronx_distributed.modules.moe.blockwise._bwmm_shard_on_block_nki_call')
    @patch('neuronx_distributed.modules.moe.blockwise.torch_to_nki_dtype')
    @patch('neuronx_distributed.modules.moe.blockwise.VNC')
    def test_basic_call_without_optional_args(self, mock_vnc, mock_torch_to_nki, mock_nki_call, sample_args):
        """Test basic kernel call without optional arguments."""
        # Setup mocks
        mock_vnc.return_value = MagicMock()
        mock_torch_to_nki.return_value = torch.bfloat16
        mock_output = torch.randn(2, 129, 512, dtype=torch.bfloat16)  # +1 for padding
        mock_nki_call.__getitem__.return_value.return_value = mock_output
        
        # Call function
        result = _call_bwmm_shard_on_block_kernel(sample_args)
        
        # Verify kernel was called
        mock_nki_call.__getitem__.assert_called_once_with(mock_vnc.return_value)
        
        # Verify output slicing for accumulating mode
        assert torch.equal(result, mock_output[0, ...])

    @patch('neuronx_distributed.modules.moe.blockwise._bwmm_shard_on_block_nki_call')
    @patch('neuronx_distributed.modules.moe.blockwise.torch_to_nki_dtype')
    @patch('neuronx_distributed.modules.moe.blockwise.VNC')
    def test_call_with_bias_tensors(self, mock_vnc, mock_torch_to_nki, mock_nki_call, sample_args):
        """Test kernel call with bias tensors."""
        # Add bias tensors
        num_experts, intermediate_size = 8, 2048
        sample_args.gate_up_proj_bias = torch.randn(num_experts, 2, intermediate_size, dtype=torch.bfloat16)
        sample_args.down_proj_bias = torch.randn(num_experts, 512, dtype=torch.bfloat16)
        
        mock_vnc.return_value = MagicMock()
        mock_torch_to_nki.return_value = torch.bfloat16
        mock_output = torch.randn(2, 129, 512, dtype=torch.bfloat16)
        mock_nki_call.__getitem__.return_value.return_value = mock_output
        
        _ = _call_bwmm_shard_on_block_kernel(sample_args)
        
        # Verify bias reshaping was applied
        call_args = mock_nki_call.__getitem__.return_value.call_args
        assert call_args[1]['gate_and_up_proj_bias'].shape == (num_experts, 2, intermediate_size)
        assert call_args[1]['down_proj_bias'] is not None

    @patch('neuronx_distributed.modules.moe.blockwise._bwmm_shard_on_block_nki_call')
    @patch('neuronx_distributed.modules.moe.blockwise.torch_to_nki_dtype')
    @patch('neuronx_distributed.modules.moe.blockwise.VNC')
    def test_call_with_clamping_limits(self, mock_vnc, mock_torch_to_nki, mock_nki_call, sample_args):
        """Test kernel call with clamping limits."""
        # Add clamping limits
        sample_args.gate_clamp_upper_limit = 6.0
        sample_args.gate_clamp_lower_limit = -6.0
        sample_args.up_clamp_upper_limit = 10.0
        sample_args.up_clamp_lower_limit = -10.0
        
        mock_vnc.return_value = MagicMock()
        mock_torch_to_nki.return_value = torch.bfloat16
        mock_output = torch.randn(2, 129, 512, dtype=torch.bfloat16)
        mock_nki_call.__getitem__.return_value.return_value = mock_output
        
        _ = _call_bwmm_shard_on_block_kernel(sample_args)
        
        # Verify clamping parameters were passed
        call_args = mock_nki_call.__getitem__.return_value.call_args
        assert call_args[1]['gate_clamp_upper_limit'] == 6.0
        assert call_args[1]['gate_clamp_lower_limit'] == -6.0
        assert call_args[1]['up_clamp_upper_limit'] == 10.0
        assert call_args[1]['up_clamp_lower_limit'] == -10.0

    @patch('neuronx_distributed.modules.moe.blockwise._bwmm_shard_on_block_nki_call')
    @patch('neuronx_distributed.modules.moe.blockwise.torch_to_nki_dtype')
    @patch('neuronx_distributed.modules.moe.blockwise.VNC')
    def test_non_accumulating_mode(self, mock_vnc, mock_torch_to_nki, mock_nki_call, sample_args):
        """Test kernel call in non-accumulating mode."""
        sample_args.is_tensor_update_accumulating = False
        
        mock_vnc.return_value = MagicMock()
        mock_torch_to_nki.return_value = torch.bfloat16
        mock_output = torch.randn(128, 512, dtype=torch.bfloat16)
        mock_nki_call.__getitem__.return_value.return_value = mock_output
        
        result = _call_bwmm_shard_on_block_kernel(sample_args)
        
        # Verify output is returned directly (no slicing)
        assert torch.equal(result, mock_output)

    @patch('neuronx_distributed.modules.moe.blockwise._bwmm_shard_on_block_nki_call')
    @patch('neuronx_distributed.modules.moe.blockwise.torch_to_nki_dtype')
    @patch('neuronx_distributed.modules.moe.blockwise.VNC')
    def test_tensor_dtype_conversions(self, mock_vnc, mock_torch_to_nki, mock_nki_call, sample_args):
        """Test proper tensor dtype conversions."""
        mock_vnc.return_value = MagicMock()
        mock_torch_to_nki.return_value = torch.bfloat16
        mock_output = torch.randn(2, 129, 512, dtype=torch.bfloat16)
        mock_nki_call.__getitem__.return_value.return_value = mock_output
        
        _ = _call_bwmm_shard_on_block_kernel(sample_args)
        
        # Verify int32 conversion for position tensors
        call_args = mock_nki_call.__getitem__.return_value.call_args
        assert call_args[1]['token_position_to_id'].dtype == torch.int32
        assert call_args[1]['block_to_expert'].dtype == torch.int32

    def test_bias_reshaping_logic(self, sample_args):
        """Test bias tensor reshaping logic."""
        num_experts, intermediate_size = 8, 2048
        sample_args.gate_up_proj_bias = torch.randn(num_experts, 2, intermediate_size)
        
        with patch('neuronx_distributed.modules.moe.blockwise._bwmm_shard_on_block_nki_call') as mock_nki_call, \
             patch('neuronx_distributed.modules.moe.blockwise.torch_to_nki_dtype'), \
             patch('neuronx_distributed.modules.moe.blockwise.VNC'):
            
            mock_output = torch.randn(2, 129, 512, dtype=torch.bfloat16)
            mock_nki_call.__getitem__.return_value.return_value = mock_output
            
            _ = _call_bwmm_shard_on_block_kernel(sample_args)
            
            # Verify bias was reshaped correctly
            call_args = mock_nki_call.__getitem__.return_value.call_args
            reshaped_bias = call_args[1]['gate_and_up_proj_bias']
            assert reshaped_bias.shape == (num_experts, 2, intermediate_size)
